[project]
name = "rust-finetuning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.0.0",
    "kernels>=0.9.0",
    "torch>=2.7.1",
    "transformers>=4.55.0",
]
